### ISSUE TITLE
broken link http://repo.tom.ru/rpm/websockrtsprepo-1-0.deb

### ISSUE THREAD

**Issue by erwanj** [SpecForge/html5_rtsp_player#1]
Hello,

can you fix the link issue?
Also, can you give us more details and maybe the source code of this package?

Thank you

**Comment by victorgrenke** [comment]
The debian repository started working fine. 

The source code of our websocket proxy is not free. This is part of our own project #Analytic NVR.
We are ready to sell it or modify to your needs for money, if you have such desire.

In any event, our html5 player is not tied to our websocket proxy and can work as an independent unit.

Regards
Victor
