### ISSUE TITLE
Link broken for ws-rtsp-repo-1.2.deb / getting 404 not found

### ISSUE THREAD

**Issue by aamoghal** [SpecForge/html5_rtsp_player#10]
The link for downloading ws-rtsp-repo-1.2.deb seems to be broken...

wget http://repo.tom.ru/deb/debian/non-free/all/ws-rtsp-repo-1.2.deb 
--2016-08-06 22:16:18--  http://repo.tom.ru/deb/debian/non-free/all/ws-rtsp-repo-1.2.deb
Resolving repo.tom.ru (repo.tom.ru)... 213.183.104.244
Connecting to repo.tom.ru (repo.tom.ru)|213.183.104.244|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-06 22:16:19 ERROR 404: Not Found.

**Comment by silvahalexandre** [comment]
It's happening again today. Yesterday I was able to download it. Does not seem to be working today though
