### ISSUE TITLE
Websocket proxy repo down

### ISSUE THREAD

**Issue by mempf** [SpecForge/html5_rtsp_player#7]
Hi there,

I was looking to trying your websocket proxy solution however when I tried to access the rpm at:
http://repo.tom.ru/rpm/websock_rtsp_repo-1-0.noarch.rpm
 I received a "ERR_NAME_NOT_RESOLVED" error on the repo.tom.ru domain. The deb package is also unavailable for the same reason it seems.

Hope this issue doesn't persist long, I'd really like to try out the server.

Thanks!

**Comment by victorgrenke** [comment]
Hello

I have checked the link it works.

May be there was problem with internet when you try to get rpm.

Try to get it again. If you will have problem let me know I can remove 
rpm to another domain name.

Regards


28.07.2016 5:55, Josh Ancill пишет:

**Comment by mempf** [comment]
Thanks, it worked when I tried this time.

**Comment by nyzm** [comment]
link is not working again.

**Comment by kreopt** [comment]
This repo does not work anymore. You should get proxy from streamers.com

4 авг. 2017 г. 8:53 пользователь "nyzm" <notifications@github.com> написал:

**Comment by kreopt** [comment]
Streamedian.com*
